configurations:
  - sources:
      include:
        - .
    templates:
      - ../../../Tools/Sourcery/Templates
    output:
      Tests/DomainTests/Generated
    args:
      autoMockableTestableImports:
        - Domain 