configurations:
  - sources:
      include:
        - .
        - ../Packages/Domain
    templates:
      - ../../Tools/Sourcery/Templates
    output:
      ../alkimiirickandmortyTests/Generated
    args:
      autoMockableTestableImports:
        - Domain