configurations:
  - sources:
      include:
        - .
        - ../Packages
    templates:
      - ../../Tools/Sourcery/Templates
    output:
      ../alkimiirickandmortyTests/Generated
    args:
      autoMockableImports:
        - Apollo
      autoMockableTestableImports:
        - Data
        - Domain
        - GraphQL